print("Hello World!")
print(1 + 2)
print(7 * 6)
print()
print("The end")
print("This is the new addition to code")

first_name = input("Please enter your first name: ")
last_name = input("Please enter your last name: ")
print("Hello", first_name, last_name, "nice to meet you!")
first_name = input("Please enter your first name: ")
last_name = input("Please enter your last name: ")
age = input("How old are you " + first_name + "? ")
print("Hello", first_name, last_name, "nice to meet you!")
print(first_name, "you were born in the year", 2023-int(age))
